name: 'tagged-release'

on:
    push:
        tags:
            - 'v*'
permissions:
    contents: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tagged-release:
        name: 'Tagged Release'
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v4.1.7
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - uses: electrovir/release-vir@dev
